cmake_minimum_required(VERSION 3.16)
project(hodlcalc VERSION 1.0.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(hodlcalc main.cpp)
if(MSVC)
  target_compile_options(hodlcalc PRIVATE /EHsc /W4 /O2)
  target_link_libraries(hodlcalc PRIVATE winhttp comdlg32 user32 gdi32 shell32)
endif()

